interface Name {
    id: number;
    name: string;
    gender: Gender;
    popularity: Popularity;
    length: Length;
  }
  
  export enum Gender {
    FEMALE = "Female",
    MALE = "Male",
    UNISEX = "Unisex",
  }
  
  export enum Popularity {
    TRENDY = "Trendy",
    UNIQUE = "Unique",
  }
  
  export enum Length {
    SHORT = "Short",
    LONG = "Long",
    ALL = "All",
  }
  export const names: Name[] = [
    {
      id: 1,
      name: "Abner",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 2,
      name: "Adelaide",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 3,
      name: "Aidan",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 4,
      name: "Aiden",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 5,
      name: "Aislinn",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 6,
      name: "Alastair",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 7,
      name: "Alexander",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 8,
      name: "Ali",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 9,
      name: "Amelia",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 10,
      name: "Ansley",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 11,
      name: "Aria",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 12,
      name: "Asher",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 13,
      name: "Ashton",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
  
    {
      id: 14,
      name: "Aspen",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 15,
      name: "Atlas",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 16,
      name: "Aurora",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 17,
      name: "Austen",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 18,
      name: "Ava",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 19,
      name: "Avani",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 20,
      name: "Avery",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 21,
      name: "Azure",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 22,
      name: "Beaux",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 23,
      name: "Benny",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 24,
      name: "Blake",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 25,
      name: "Boaz",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 26,
      name: "Briar",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
  
    {
      id: 27,
      name: "Caleb",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 28,
      name: "Campbell",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 29,
      name: "Casey",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 30,
      name: "Charlie",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 31,
      name: "Charlotte",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 32,
      name: "Coen",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
  
    {
      id: 33,
      name: "Cordelia",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
  
    {
      id: 34,
      name: "Crue",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 35,
      name: "Dakota",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 36,
      name: "Declan",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 37,
      name: "Duncan",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 38,
      name: "Dylan",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 39,
      name: "Echo",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 40,
      name: "Eden",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 41,
      name: "Ellis",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 42,
      name: "Emmerson",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 43,
      name: "Ethan",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 44,
      name: "Evan",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 45,
      name: "Evelyn",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 46,
      name: "Everett",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 47,
      name: "Ezra",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 48,
      name: "Felix",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 49,
      name: "Finley",
      gender: Gender.UNISEX,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 50,
      name: "Finn",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 51,
      name: "Foster",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 52,
      name: "Freya",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 53,
      name: "Genevieve",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 54,
      name: "Gianni",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 55,
      name: "Harlow",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 56,
      name: "Harper",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 57,
      name: "Harris",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 58,
      name: "Hazel",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 59,
      name: "Hunter",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 60,
      name: "Ingrid",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 61,
      name: "Iris",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 62,
      name: "Isla",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 63,
      name: "Ivy",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 64,
      name: "Jaelynn",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 65,
      name: "Jasper",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 66,
      name: "Jaylin",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 67,
      name: "Jillian",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 68,
      name: "Jream",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 69,
      name: "Jude",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 70,
      name: "Juelz",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 71,
      name: "Kacey",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 72,
      name: "Kai",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 73,
      name: "Kaya",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 74,
      name: "Kaylie",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 75,
      name: "Leo",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 76,
      name: "Levi",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 77,
      name: "Liam",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 78,
      name: "Lilia",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 79,
      name: "Lily",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 80,
      name: "Logan",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 81,
      name: "Love",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 82,
      name: "Luca",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 83,
      name: "Luna",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 84,
      name: "Lyle",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 85,
      name: "Maeve",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 86,
      name: "Majesty",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 87,
      name: "Marc",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 88,
      name: "Mayson",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 89,
      name: "Merrick",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 90,
      name: "Noah",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 91,
      name: "Nori",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 92,
      name: "Nova",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 93,
      name: "Oliver",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 94,
      name: "Olivia",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 95,
      name: "Orion",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 96,
      name: "Quinn",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 97,
      name: "Riley",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 98,
      name: "River",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 99,
      name: "Rogelio",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 100,
      name: "Ronnie",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 101,
      name: "Rory",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 102,
      name: "Rosalina",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 103,
      name: "Rowan",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 104,
      name: "Saanvi",
      gender: Gender.FEMALE,
      popularity: Popularity.UNIQUE,
      length: Length.LONG,
    },
    {
      id: 105,
      name: "Sage",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 106,
      name: "Sebastian",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 107,
      name: "Sevyn",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 108,
      name: "Silas",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
    {
      id: 109,
      name: "Sophia",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 110,
      name: "Stone",
      gender: Gender.MALE,
      popularity: Popularity.UNIQUE,
      length: Length.SHORT,
    },
    {
      id: 111,
      name: "Theodore",
      gender: Gender.MALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 112,
      name: "Violet",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 113,
      name: "Willow",
      gender: Gender.UNISEX,
      popularity: Popularity.TRENDY,
      length: Length.LONG,
    },
    {
      id: 114,
      name: "Wren",
      gender: Gender.FEMALE,
      popularity: Popularity.TRENDY,
      length: Length.SHORT,
    },
  ];